"""initial schema

Revision ID: 0f88871b47c6
Revises:
Create Date: 2026-09-14 11:18:27.586428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f88871b47c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('name', name=op.f('uq_services_name'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CA', 'SUB_CA', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_clients_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_pan_number'), 'clients', ['pan_number'], unique=False)
    op.create_table('sub_services',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_sub_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_services'))
    )
    op.create_table('document_requests',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('sub_service_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_document_requests_client_id_clients')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_document_requests_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_document_requests_service_id_services')),
    sa.ForeignKeyConstraint(['sub_service_id'], ['sub_services.id'], name=op.f('fk_document_requests_sub_service_id_sub_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requests'))
    )
    op.create_index(op.f('ix_document_requests_client_id'), 'document_requests', ['client_id'], unique=False)
    op.create_table('requested_documents',
    sa.Column('document_request_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_request_id'], ['document_requests.id'], name=op.f('fk_requested_documents_document_request_id_document_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requested_documents'))
    )
    op.create_index(op.f('ix_requested_documents_document_request_id'), 'requested_documents', ['document_request_id'], unique=False)
    op.create_table('document_uploads',
    sa.Column('requested_document_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_public_id', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'VALID', 'INVALID', 'NEEDS_REVIEW', 'EXPIRED', name='upload_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_document_uploads_client_id_clients')),
    sa.ForeignKeyConstraint(['requested_document_id'], ['requested_documents.id'], name=op.f('fk_document_uploads_requested_document_id_requested_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_uploads'))
    )
    op.create_index(op.f('ix_document_uploads_client_id'), 'document_uploads', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_uploads_requested_document_id'), 'document_uploads', ['requested_document_id'], unique=False)
    op.create_table('requirements',
    sa.Column('requested_document_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_INTERPRETATION', 'INTERPRETED', 'FAILED', name='requirement_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_document_id'], ['requested_documents.id'], name=op.f('fk_requirements_requested_document_id_requested_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('requested_document_id', name=op.f('uq_requirements_requested_document_id'))
    )
    op.create_table('ai_processing_results',
    sa.Column('document_upload_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('CLASSIFICATION', 'EXTRACTION', 'REQUIREMENT_UNDERSTANDING', name='processing_stage'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_uploads.id'], name=op.f('fk_ai_processing_results_document_upload_id_document_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_processing_results'))
    )
    op.create_index(op.f('ix_ai_processing_results_document_upload_id'), 'ai_processing_results', ['document_upload_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_upload_id', sa.UUID(), nullable=False),
    sa.Column('requested_document_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('storage_public_id', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_documents_client_id_clients')),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_uploads.id'], name=op.f('fk_documents_document_upload_id_document_uploads')),
    sa.ForeignKeyConstraint(['requested_document_id'], ['requested_documents.id'], name=op.f('fk_documents_requested_document_id_requested_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('document_upload_id', name=op.f('uq_documents_document_upload_id'))
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_requested_document_id'), 'documents', ['requested_document_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('document_upload_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REQUEST_REUPLOAD', name='review_decision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_uploads.id'], name=op.f('fk_review_actions_document_upload_id_document_uploads')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_review_actions_reviewed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_actions'))
    )
    op.create_index(op.f('ix_review_actions_document_upload_id'), 'review_actions', ['document_upload_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('document_upload_id', sa.UUID(), nullable=False),
    sa.Column('check_name', sa.String(length=150), nullable=False),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'UNCERTAIN', name='validation_check_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_uploads.id'], name=op.f('fk_validation_results_document_upload_id_document_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index(op.f('ix_validation_results_document_upload_id'), 'validation_results', ['document_upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_document_upload_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_review_actions_document_upload_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_documents_requested_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_processing_results_document_upload_id'), table_name='ai_processing_results')
    op.drop_table('ai_processing_results')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_document_uploads_requested_document_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_client_id'), table_name='document_uploads')
    op.drop_table('document_uploads')
    op.drop_index(op.f('ix_requested_documents_document_request_id'), table_name='requested_documents')
    op.drop_table('requested_documents')
    op.drop_index(op.f('ix_document_requests_client_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_table('sub_services')
    op.drop_index(op.f('ix_clients_pan_number'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
